services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-ubuntu-dev-box}
    ports:
      - "2224:22"
    volumes:
      - dev-home:/home/dev
    restart: unless-stopped
    labels:
      - coolify.managed=true

volumes:
  dev-home:
    driver: local
