services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    container_name: ${COMPOSE_PROJECT_NAME:-ubuntu-dev-box}
    ports:
      - "2222:22"
    volumes:
      - dev-home:/home/dev
    restart: unless-stopped
    labels:
      - coolify.managed=true
    environment:
      - DOCKER_BUILDKIT=1

volumes:
  dev-home:
    driver: local
